# Generated by Django 4.2 on 2023-04-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water_data',
            name='Reservoir_name',
            field=models.CharField(default='def', max_length=50),
        ),
    ]
