# Generated by Django 4.2 on 2023-04-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0002_alter_water_data_reservoir_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water_data',
            name='WaterLevel',
            field=models.IntegerField(),
        ),
    ]
